apps/user_app/urls.py
from django.conf.urls import url
from . import views
app_name = 'users'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^signin$', views.sign_in, name='sign_in'),
    url(r'^register$', views.register, name='register'),
    url(r'^registerTest$', views.register_test, name='register_test'),
    url(r'^signIn_test$', views.signIn_test, name='signIn_test'),
]

user_dashboard/urls.py
from django.conf.urls import url, include

urlpatterns = [
    url(r'^', include('apps.user_app.urls', namespace='users')),
    url(r'^main/', include('apps.main_app.urls', namespace='main')),
]

apps/user_app/models.py
from __future__ import unicode_literals
from django.db import models
import bcrypt, re
EMAIL_REGEX = re.compile(r"^[^@\s]+@[^@\s]+\.[^@\s]+$")


class UserManager(models.Manager):
    def create_user(self, data):
        errors = {}
        if not data['first_name'] or len(data['first_name']) < 2 or not data['last_name'] or len(data['last_name']) < 2:
            errors['name'] = 'Enter a valid name'
        if not data['email'] or not EMAIL_REGEX.match(data['email']):
            errors['email'] = 'Enter a valid email'
        if self.filter(email=data['email']):
            errors['email_exist'] = 'Email already exist'
        if not data['password'] or len(data['password']) < 6:
            errors['password'] = 'Enter a password of 8  xters or up'
        if not data['confirm_password'] or data['confirm_password'] != data['password']:
            errors['confirm_password'] = 'Enter a matching password'
        if len(errors):
            return errors
        else:
            hash_password = bcrypt.hashpw(data['password'].encode(), bcrypt.gensalt())
            return self.create(first_name=data['first_name'], last_name=data['last_name'], user_type=False, email=data['email'], password=hash_password)

    def validate_user(self, data):
        errors = {}
        if self.filter(email=data['email']):
            user = self.get(email=data['email'])
            hash_password = bcrypt.hashpw(data['password'].encode(), user.password.encode())
            if (hash_password == user.password):
                return user
            else:
                errors['password'] = 'Invalid Password'
        else:
            errors['email'] = 'Invalid Email'
        return errors

    def update_info(self, data, user_id):
        errors = {}
        if not data['first_name'] or len(data['first_name']) < 2 or not data['last_name'] or len(data['last_name']) < 2:
            errors['name'] = 'Enter a valid name'
        if not data['email'] or not EMAIL_REGEX.match(data['email']):
            errors['email'] = 'Enter a valid email'
        if self.exclude(id=user_id).filter(email=data['email']):
            errors['email_exist'] = 'Email already exist'
        if len(errors):
            return errors
        else:
            return self.filter(id=user_id).update(first_name=data['first_name'], last_name=data['last_name'], email=data['email'])

    def update_password(self, data, user_id):
        errors = {}
        if not data['password'] or len(data['password']) < 6:
            errors['password'] = 'Enter a password of 8  xters or up'
        if not data['confirm_password'] or data['confirm_password'] != data['password']:
            errors['confirm_password'] = 'Enter a matching password'
        if len(errors):
            return errors
        else:
            hash_password = bcrypt.hashpw(data['password'].encode(), bcrypt.gensalt())
            return self.filter(id=user_id).update(password=hash_password)

    def update_description(self, data, user_id):
        error = {}
        if not len(data['description']):
            error['description'] = 'Field can not be empty'
            return error
        else:
            return self.filter(id=user_id).update(description=data['description'])

    def delete_user(self, user_id):
        return self.filter(id=user_id).delete()        


# Create your models here.
class User(models.Model):
    first_name = models.CharField(max_length=25)
    last_name = models.CharField(max_length=25)
    email = models.CharField(max_length=25)
    password = models.CharField(max_length=25)
    description = models.TextField(max_length=1000, default='')
    user_type = models.BooleanField(default=True)
    created_at= models.DateTimeField(auto_now_add=True)
    updated_at= models.DateTimeField(auto_now=True)
    objects = UserManager()

apps/user_app/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .models import User

# Create your views here.
def index(request):
    return render(request, 'user_app/index.html')

def sign_in(request):
    return render(request, 'user_app/sign_in.html')

def register(request):
    return render(request, 'user_app/register.html')

def register_test(request):
    entry = User.objects.create_user(request.POST)
    if not type(entry) is dict:
        if entry.user_type == True:
            request.session['user_id'] = entry.id
            return redirect('main:dashboard_admin')
        else:
            request.session['user_id'] = entry.id
            return redirect('main:dashboard_user')
    else:
        if 'name' in entry:
            messages.add_message(request, messages.INFO, entry['name'], extra_tags='sign_up')
        if 'email' in entry:
            messages.add_message(request, messages.INFO, entry['email'], extra_tags='sign_up')
        if 'password' in entry:
            messages.add_message(request, messages.INFO, entry['password'], extra_tags='sign_up')
        if 'confirm_password' in entry:
            messages.add_message(request, messages.INFO, entry['confirm_password'], extra_tags='sign_up')
        if 'email_exist' in entry:
            messages.add_message(request, messages.INFO, entry['email_exist'], extra_tags='sign_up')
        return redirect('users:register')

def signIn_test(request):
    entry = User.objects.validate_user(request.POST)
    if not type(entry) is dict:
        if entry.user_type == True:
            request.session['user_id'] = entry.id
            return redirect('main:dashboard_admin')
        else:
            request.session['user_id'] = entry.id
            return redirect('main:dashboard_user')
    else:
        if 'email' in entry:
            messages.add_message(request, messages.INFO, entry['email'], extra_tags='log_in')
        if 'password' in entry:
            messages.add_message(request, messages.INFO, entry['password'], extra_tags='log_in')
        return redirect('users:sign_in')

apps/user_app/templates/user_app/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
    <style media="screen">
      main{
        width: 80%;
        margin: auto;
        background-color: blue;
        padding: 10px;
      }
      form{
        padding: 20px;
      }
    </style>
  </head>
  <body>
    <main>
      <h1>Welcome to the Test</h1>
      <h2>We are going to build a cool application using a MVC framework! This app was built by Wura</h2>
      <form  action="{% url 'users:sign_in' %}" method="post">
        {% csrf_token %}
        <input type="submit" value="Start">
      </form>
    </main>
  </body>
</html>

apps/user_app/templates/user_app/register.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h2>Sign In</h2>
    <form  action="{% url 'users:register_test' %}" method="post">
      {% csrf_token %}
      <input type="text" name="first_name" placeholder="first name"><p></p>
      <input type="text" name="last_name" placeholder="last name"><p></p>
      <input type="email" name="email" placeholder="email address"><p></p>
      <input type="text" name="password"  placeholder="password"><p></p>
      <input type="text" name="confirm_password"  placeholder="confirm password"><p></p>
      <input type="submit" value="Register">
    </form>
    {% if messages %}
      {% for message in messages %}
        {% if 'sign_up' in message.tags %}
           <p>{{message}}</p>
        {% endif %}
      {% endfor %}
    {% endif %}
    <p><a href="{% url 'users:sign_in' %}">Already have an account? Login</a></p>
  </body>
</html>

apps/user_app/templates/user_app/sign_in.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h2>Sign In</h2>
    <form  action="{% url 'users:signIn_test' %}" method="post">
      {% csrf_token %}
      <input type="email" name="email" placeholder="email address"><p></p>
      <input type="text" name="password" placeholder="password"><p></p>
      <input type="submit" value="Sign In"><p></p>
      {% if messages %}
        {% for message in messages %}
          {% if 'log_in' in message.tags %}
             <p>{{message}}</p>
          {% endif %}
        {% endfor %}
      {% endif %}
    </form>
    <p><a href="{% url 'users:register' %}">Dont have an account? Register</a></p>
  </body>
</html>