apps/main_app/urls.py
from django.conf.urls import url
from . import views
app_name = 'main'

urlpatterns = [
    url(r'^dashboard/admin$', views.dashboard_admin, name='dashboard_admin'),
    url(r'^dashboard$', views.dashboard_user, name='dashboard_user'),
    url(r'^user/new$', views.add_user, name='add_user'),
    url(r'^createUser$', views.create_user, name='create_user'),
    url(r'^user/edit/(?P<user_id>\d+)$', views.edit_profile, name='edit_profile'),
    url(r'^user/edit_info/(?P<user_id>\d+)$', views.edit_info, name='edit_info'),
    url(r'^user/change_password/(?P<user_id>\d+)$', views.change_password, name='change_password'),
    url(r'^user/change_description/(?P<user_id>\d+)$', views.change_description, name='change_description'),
    url(r'^user/remove_user/(?P<user_id>\d+)$', views.remove_page, name='remove_page'),
    url(r'^user/delete/(?P<user_id>\d+)$', views.delete_this_user, name='delete_user'),
    url(r'^user/show/(?P<user_id>\d+)$', views.view_user, name='view_user'),
    url(r'^user/add_message/(?P<user_id>\d+)$', views.post_message, name='post_message'),
]

apps/user_app/urls.py
from django.conf.urls import url
from . import views
app_name = 'users'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^signin$', views.sign_in, name='sign_in'),
    url(r'^register$', views.register, name='register'),
    url(r'^registerTest$', views.register_test, name='register_test'),
    url(r'^signIn_test$', views.signIn_test, name='signIn_test'),
]

user_dashboard/urls.py
from django.conf.urls import url, include

urlpatterns = [
    url(r'^', include('apps.user_app.urls', namespace='users')),
    url(r'^main/', include('apps.main_app.urls', namespace='main')),
]

apps/main_app/models.py
from __future__ import unicode_literals
from django.db import models
from ..user_app.models import User

# Create your models here.
class MessageManager(models.Manager):
    def create_message(self, data, sender, recipient):
        error = {}
        if not data['message']:
            error['empty'] = 'Text field is empty'
            return error
        else:
            return self.create(sender=sender, recipient=recipient, message=data['message'])

class CommentManager(models.Manager):
    def create_comment(self, data, user, message):
        error = {}
        if not data['comment']:
            error['empty'] = 'Text field is empty'
            return error
        else:
            return self.create(comment=data['comment'], user=user, message=message)


class Message(models.Model):
    sender = models.ForeignKey(User, related_name='sent_messages')
    recipient = models.ForeignKey(User, related_name='received_messages')
    message = models.TextField(max_length=2000)
    created_at= models.DateTimeField(auto_now_add=True)
    updated_at= models.DateTimeField(auto_now=True)
    objects = MessageManager()


class Comment(models.Model):
    user = models.ForeignKey(User, related_name='user_comments')
    message = models.ForeignKey(Message, related_name='message_comments')
    comment = models.TextField(max_length=2000)
    created_at= models.DateTimeField(auto_now_add=True)
    updated_at= models.DateTimeField(auto_now=True)
    objects = CommentManager()

apps/main_app/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from ..user_app.models import User
from .models import Message, Comment
from django.core.urlresolvers import reverse

# Create your views here.
def dashboard_admin(request):
    if User.objects.filter(id=request.session['user_id']):
        user = User.objects.get(id=request.session['user_id'])
        context = {'user': user, 'users': User.objects.all()}
    return render(request, 'main_app/dashboard_admin.html', context)


def dashboard_user(request):
    if User.objects.filter(id=request.session['user_id']):
        user = User.objects.get(id=request.session['user_id'])
        context = {'user': user, 'users': User.objects.all()}
    return render(request, 'main_app/dashboard.html', context)

def add_user(request):
    return render(request, 'main_app/add_user.html')

def create_user(request):
    entry = User.objects.create_user(request.POST)
    if not type(entry) is dict:
        return redirect('main:dashboard_admin')
    else:
        if 'name' in entry:
            messages.add_message(request, messages.INFO, entry['name'], extra_tags='sign_up')
        if 'email' in entry:
            messages.add_message(request, messages.INFO, entry['email'], extra_tags='sign_up')
        if 'password' in entry:
            messages.add_message(request, messages.INFO, entry['password'], extra_tags='sign_up')
        if 'confirm_password' in entry:
            messages.add_message(request, messages.INFO, entry['confirm_password'], extra_tags='sign_up')
        if 'email_exist' in entry:
            messages.add_message(request, messages.INFO, entry['email_exist'], extra_tags='sign_up')
        return redirect('main:add_user')

def edit_profile(request, user_id):
    user = User.objects.get(id=user_id)
    context = {'user': user}
    return render(request, 'main_app/edit_profile.html', context)

def edit_info(request, user_id):
    entry = User.objects.update_info(request.POST, user_id)
    if not type(entry) is dict:
        current_user = User.objects.get(id=request.session['user_id'])
        if current_user.user_type == True:
            return redirect('main:dashboard_admin')
        else:
            return redirect('main:dashboard_user')
    else:
        if 'name' in entry:
            messages.add_message(request, messages.INFO, entry['name'], extra_tags='edit_info')
        if 'email' in entry:
            messages.add_message(request, messages.INFO, entry['email'], extra_tags='edit_info')
        if 'email_exist' in entry:
            messages.add_message(request, messages.INFO, entry['email_exist'], extra_tags='sign_up')
        return redirect('main:edit_profile')


def change_password(request, user_id):
    entry = User.objects.update_password(request.POST, user_id)
    if not type(entry) is dict:
        current_user = User.objects.get(id=request.session['user_id'])
        if current_user.user_type == True:
            return redirect('main:dashboard_admin')
        else:
            return redirect('main:dashboard_user')
    else:
        if 'password' in entry:
            messages.add_message(request, messages.INFO, entry['password'], extra_tags='password')
        if 'confirm_password' in entry:
            messages.add_message(request, messages.INFO, entry['confirm_password'], extra_tags='password')
        return redirect('main:edit_profile')

def change_description(request, user_id):
    entry = User.objects.update_description(request.POST, user_id)
    print 'ON TOP', entry, 'GHGHJgd'
    if not type(entry) is dict:
        current_user = User.objects.get(id=request.session['user_id'])
        if current_user.user_type == True:
            return redirect('main:dashboard_admin')
        else:
            return redirect('main:dashboard_user')
    else:
        if 'description' in entry:
            messages.add_message(request, messages.INFO, entry['description'], extra_tags='description')
        return redirect('main:edit_profile')

def remove_page(request, user_id):
    user = User.objects.get(id=user_id)
    context = {'user': user}
    return render(request, 'main_app/delete.html', context)


def delete_this_user(request, user_id):
    print User.objects.delete_user(user_id)
    return redirect('main:dashboard_admin')


def view_user(request, user_id):
    user = User.objects.get(id=user_id)
    messages = Message.objects.filter(recipient=user).order_by('-created_at')
    context = {'user': user, 'messages': messages}
    return render(request, 'main_app/show_user.html', context)


def post_message(request, user_id):
    recipient = User.objects.get(id=user_id)
    sender = User.objects.get(id=request.session['user_id'])
    Message.objects.create_message(request.POST, sender, recipient)
    return redirect(reverse('main:view_user', kwargs={'user_id': user_id }))

apps/main_app/templates/main_app/add_user.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <button type="button" name="button"><a href="{% url 'main:dashboard_admin' %}">Return To Dashboard</a></button>
    <h2>Add a new user</h2>
    <form  action="{% url 'main:create_user' %}" method="post">
      {% csrf_token %}
      <input type="text" name="first_name" placeholder="first name"><p></p>
      <input type="text" name="last_name" placeholder="last name"><p></p>
      <input type="email" name="email" placeholder="email address"><p></p>
      <input type="text" name="password"  placeholder="password"><p></p>
      <input type="text" name="confirm_password"  placeholder="confirm password"><p></p>
      <input type="submit" value="Create">
    </form>
    {% if messages %}
      {% for message in messages %}
        {% if 'sign_up' in message.tags %}
           <p>{{message}}</p>
        {% endif %}
      {% endfor %}
    {% endif %}
  </body>
</html>

apps/main_app/templates/main_app/dashboard.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <style>
    table{
      border-collapse: collapse;
    }
    table, tr, td {
        padding: 5px;
        border: 1px solid black;
    }
  </style>
  <body>
    <div class="">
      <h3>All Users</h3>
      <p>Welcome {{user.first_name}}</p>
      <button type="button" name="button"><a href="{% url 'main:edit_profile' user_id=user.id %}">Edit Profile</a></button>
    </div>
    <a href="{% url 'users:sign_in' %}">Log Out</a>
    <table>
      <th>
        <td>ID</td>
        <td>NAME</td>
        <td>EMAIL</td>
        <td>CREATED_AT</td>
        <td>USER_LEVEL</td>
      </th>

      {% for user in users %}
        <tr>
          <td></td>
          <td>{{user.id}}</td>
          <td><a href="{% url 'main:view_user' user_id=user.id %}">{{user.first_name}}</a></td>
          <td>{{user.email}}</td>
          <td>{{user.created_at}}</td>
          <td>normal</td>
        </tr>
      {% endfor %}
    </table>
    <h4>Your bio</h4>
    <p>{{user.last_name}}</p>
    <p>{{user.description}}</p>
    <p>{{user.email}}</p>
  </body>
</html>

apps/main_app/templates/main_app/dashboard_admin.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <style>
    table{
      border-collapse: collapse;
    }
    table, tr, td {
        padding: 5px;
        border: 1px solid black;
    }
  </style>
  <body>
    <div>
      <h3>Manage Users</h3>
      <p>Welcome {{user.first_name}}</p>
      <form action="{% url 'main:add_user' %}" method="post">
        {% csrf_token %}
        <input type="submit" value="Add New User">
      </form>
    </div>
    <a href="{% url 'users:sign_in' %}">Log Out</a>
    <table>
      <th>
        <td>ID</td>
        <td>NAME</td>
        <td>EMAIL</td>
        <td>CREATED_AT</td>
        <td>USER_LEVEL</td>
        <td>ACTIONS</td>
      </th>

      {% for user in users %}
        {% if user.user_type == True %}
        <tr>
          <td></td>
          <td>{{user.id}}</td>
          <td><a href="{% url 'main:view_user' user_id=user.id %}">{{user.first_name}}</a></td>
          <td>{{user.email}}</td>
          <td>{{user.created_at}}</td>
          <td>admin</td>
          <td><a href="{% url 'main:edit_profile' user_id=user.id %}">edit</a> <a href="{% url 'main:remove_page' user_id=user.id %}">remove</a></td>
        </tr>
        {% else %}
        <tr>
          <td></td>
          <td>{{user.id}}</td>
          <td><a href="{% url 'main:view_user' user_id=user.id %}">{{user.first_name}}</a></td>
          <td>{{user.email}}</td>
          <td>{{user.created_at}}</td>
          <td>normal</td>
          <td><a href="{% url 'main:edit_profile' user_id=user.id %}">edit</a> <a href="{% url 'main:remove_page' user_id=user.id %}">remove</a></td>
        </tr>
        {% endif %}
      {% endfor %}

    </table>
  </body>
</html>

apps/main_app/templates/main_app/delete.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h3>Are you sure you want to delete {{user.first_name}}</h3>
    <p><a href="{% url 'main:delete_user' user_id=user.id %}">Yes</a></p>
    <p><a href="{% url 'main:dashboard_admin' %}">No</a></p>
  </body>
</html>

apps/main_app/templates/main_app/edit_profile.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
    <style media="screen">
      div{
        display: inline-block;
        border: 2px black solid;
        padding: 20px;
        margin: 20px;
      }
      section{
        border: 2px black solid;
        padding: 20px;
        margin: 20px;
      }
    </style>
  </head>
  <body>
    <h1>Edit Profile</h1>
    <main>
      <div>
        Edit Information
        <form  action="{% url 'main:edit_info' user_id=user.id %}" method="post">
          {% csrf_token %}
          <input type="text" name="first_name" value="{{user.first_name}}"><p></p>
          <input type="text" name="last_name" value="{{user.last_name}}"><p></p>
          <input type="email" name="email" value="{{user.email}}"><p></p>
          <input type="submit" value="Save">
        </form>
      </div>
      {% if messages %}
        {% for message in messages %}
          {% if 'edit_info' in message.tags %}
             <p>{{message}}</p>
          {% endif %}
        {% endfor %}
      {% endif %}
      <div>
        Change Password
        <form  action="{% url 'main:change_password' user_id=user.id %}" method="post">
          {% csrf_token %}
          <input type="text" name="password"  placeholder="password"><p></p>
          <input type="text" name="confirm_password"  placeholder="confirm password"><p></p>
          <input type="submit" value="Update Password">
        </form>
      </div>
      {% if messages %}
        {% for message in messages %}
          {% if 'password' in message.tags %}
             <p>{{message}}</p>
          {% endif %}
        {% endfor %}
      {% endif %}
    </main>

    <section>
      Edit Description
      <form action="{% url 'main:change_description' user_id=user.id %}" method="post">
        {% csrf_token %}
        <textarea name="description" rows="8" cols="80"></textarea>
        <input type="submit" value="Save">
      </form>
    </section>
    {% if messages %}
      {% for message in messages %}
        {% if 'description' in message.tags %}
           <p>{{message}}</p>
        {% endif %}
      {% endfor %}
    {% endif %}
  </body>
</html>

apps/main_app/templates/main_app/show_user.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>{{user.first_name}}</h1>
    <h3>ID: {{user.id}}</h3>
    <h3>Registered on: {{user.created_at}}</h3>
    <h3>Registered on: {{user.email}}</h3>
    <h3>Description: {{user.description}}</h3>

    <form action="{% url 'main:post_message' user_id=user.id %}" method="post">
      <p>Leave a message for {{user.first_name}}</p>
      {% csrf_token %}
      <textarea name="message" rows="8" cols="80"></textarea>
      <input type="submit" value="Post">
    </form>

    {% for message in messages %}
    {% load humanize %}
      <p>{{message.sender.first_name}} wrote - {{message.created_at|naturaltime}}</p>
      <h4>{{message.message}}</h4>
    {% endfor %}
  </body>
</html>